// Auto-generated by /tmp/build-api-index.py — do not hand-edit.
import type { Pkg } from '../components/SymbolTree.astro';

export interface ApiSection {
  id: string;
  title: string;
  packages: Pkg[];
}

export const sections: ApiSection[] = [
  {
    id: 'core',
    title: 'Core runtime',
    packages: [
      {
        name: '@triggery/core',
        url: '/packages/core/',
        blurb: 'runtime, indexed dispatch, scheduler, inspector, middleware',
        symbols: [
          {
            name: 'createCheck',
            kind: 'function',
            url: '/api/core/create-check/',
          },
          {
            name: 'createInspector',
            kind: 'function',
            url: '/api/core/create-inspector/',
          },
          {
            name: 'createRuntime',
            kind: 'function',
            url: '/api/core/create-runtime/',
          },
          {
            name: 'createScheduler',
            kind: 'function',
            url: '/api/core/create-scheduler/',
          },
          {
            name: 'createTrigger',
            kind: 'function',
            url: '/api/core/create-trigger/',
          },
          {
            name: 'getDefaultRuntime',
            kind: 'function',
            url: '/api/core/get-default-runtime/',
          },
          {
            name: 'setDefaultRuntime',
            kind: 'function',
            url: '/api/core/set-default-runtime/',
          },
          {
            name: 'ActionContext',
            kind: 'type',
          },
          {
            name: 'ActionFn',
            kind: 'type',
          },
          {
            name: 'ActionHook',
            kind: 'type',
          },
          {
            name: 'ActionKey',
            kind: 'type',
          },
          {
            name: 'ActionMap',
            kind: 'type',
          },
          {
            name: 'ActionsCtx',
            kind: 'type',
          },
          {
            name: 'CascadeContext',
            kind: 'type',
          },
          {
            name: 'CheckCtx',
            kind: 'type',
          },
          {
            name: 'ConcurrencyStrategy',
            kind: 'type',
          },
          {
            name: 'ConditionGetter',
            kind: 'type',
          },
          {
            name: 'ConditionHook',
            kind: 'type',
          },
          {
            name: 'ConditionKey',
            kind: 'type',
          },
          {
            name: 'ConditionMap',
            kind: 'type',
          },
          {
            name: 'ConditionsCtx',
            kind: 'type',
          },
          {
            name: 'CreateTriggerConfig',
            kind: 'type',
          },
          {
            name: 'EmptyRecord',
            kind: 'type',
          },
          {
            name: 'EventHook',
            kind: 'type',
          },
          {
            name: 'EventKey',
            kind: 'type',
          },
          {
            name: 'EventMap',
            kind: 'type',
          },
          {
            name: 'EventOf',
            kind: 'type',
          },
          {
            name: 'FireContext',
            kind: 'type',
          },
          {
            name: 'InspectorImpl',
            kind: 'type',
          },
          {
            name: 'InternalHandlerCtx',
            kind: 'type',
          },
          {
            name: 'InternalTriggerConfig',
            kind: 'type',
          },
          {
            name: 'MatchContext',
            kind: 'type',
          },
          {
            name: 'MetaCtx',
            kind: 'type',
          },
          {
            name: 'Middleware',
            kind: 'type',
            url: '/api/core/types/middleware/',
          },
          {
            name: 'NamedHooks',
            kind: 'type',
          },
          {
            name: 'RegisterScopeOptions',
            kind: 'type',
          },
          {
            name: 'RegistrationToken',
            kind: 'type',
          },
          {
            name: 'Runtime',
            kind: 'type',
          },
          {
            name: 'RuntimeGraph',
            kind: 'type',
          },
          {
            name: 'RuntimeOptions',
            kind: 'type',
            url: '/api/core/types/runtime-options/',
          },
          {
            name: 'SchedulerImpl',
            kind: 'type',
          },
          {
            name: 'SchedulerStrategy',
            kind: 'type',
          },
          {
            name: 'SkipContext',
            kind: 'type',
          },
          {
            name: 'Task',
            kind: 'type',
          },
          {
            name: 'ToPascal',
            kind: 'type',
          },
          {
            name: 'Trigger',
            kind: 'type',
          },
          {
            name: 'TriggerConfig',
            kind: 'type',
          },
          {
            name: 'TriggerCtx',
            kind: 'type',
            url: '/api/core/types/trigger-ctx/',
          },
          {
            name: 'TriggerGraphNode',
            kind: 'type',
          },
          {
            name: 'TriggerHandler',
            kind: 'type',
          },
          {
            name: 'TriggerInspectSnapshot',
            kind: 'type',
          },
          {
            name: 'TriggerSchema',
            kind: 'type',
            url: '/api/core/types/trigger-schema/',
          },
          {
            name: 'UntypedActionFn',
            kind: 'type',
          },
        ],
      },
    ],
  },
  {
    id: 'bindings',
    title: 'Framework bindings',
    packages: [
      {
        name: '@triggery/react',
        url: '/packages/react/',
        blurb: 'React 18+/19 hooks + providers',
        symbols: [
          {
            name: 'createNamedHooks',
            kind: 'function',
            url: '/api/react/create-named-hooks/',
          },
          {
            name: 'useAction',
            kind: 'function',
            url: '/api/react/use-action/',
          },
          {
            name: 'useCondition',
            kind: 'function',
            url: '/api/react/use-condition/',
          },
          {
            name: 'useEvent',
            kind: 'function',
            url: '/api/react/use-event/',
          },
          {
            name: 'useInlineTrigger',
            kind: 'function',
            url: '/api/react/use-inline-trigger/',
          },
          {
            name: 'useInspect',
            kind: 'function',
            url: '/api/react/use-inspect/',
          },
          {
            name: 'useInspectHistory',
            kind: 'function',
            url: '/api/react/use-inspect-history/',
          },
          {
            name: 'useRuntime',
            kind: 'function',
          },
          {
            name: 'useScope',
            kind: 'function',
          },
          {
            name: 'TriggerRuntimeContext',
            kind: 'component',
          },
          {
            name: 'TriggerRuntimeProvider',
            kind: 'component',
            url: '/api/react/trigger-runtime-provider/',
          },
          {
            name: 'TriggerScope',
            kind: 'component',
            url: '/api/react/trigger-scope/',
          },
          {
            name: 'TriggerScopeContext',
            kind: 'component',
          },
          {
            name: 'TriggerRuntimeProviderProps',
            kind: 'type',
          },
          {
            name: 'TriggerScopeProps',
            kind: 'type',
          },
          {
            name: 'UseInlineTriggerConfig',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/solid',
        url: '/packages/solid/',
        blurb: 'SolidJS bindings, native reactivity',
        symbols: [
          {
            name: 'useAction',
            kind: 'function',
            url: '/api/react/use-action/',
          },
          {
            name: 'useCondition',
            kind: 'function',
            url: '/api/react/use-condition/',
          },
          {
            name: 'useEvent',
            kind: 'function',
            url: '/api/react/use-event/',
          },
          {
            name: 'useInlineTrigger',
            kind: 'function',
            url: '/api/react/use-inline-trigger/',
          },
          {
            name: 'useInspect',
            kind: 'function',
            url: '/api/react/use-inspect/',
          },
          {
            name: 'useInspectHistory',
            kind: 'function',
            url: '/api/react/use-inspect-history/',
          },
          {
            name: 'useRuntime',
            kind: 'function',
          },
          {
            name: 'useScope',
            kind: 'function',
          },
          {
            name: 'RuntimeContext',
            kind: 'component',
          },
          {
            name: 'ScopeContext',
            kind: 'component',
          },
          {
            name: 'TriggerRuntimeProvider',
            kind: 'component',
            url: '/api/react/trigger-runtime-provider/',
          },
          {
            name: 'TriggerScope',
            kind: 'component',
            url: '/api/react/trigger-scope/',
          },
          {
            name: 'UseInlineTriggerConfig',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/vue',
        url: '/packages/vue/',
        blurb: 'Vue 3 Composition API bindings',
        symbols: [
          {
            name: 'provideTriggerRuntime',
            kind: 'function',
          },
          {
            name: 'provideTriggerScope',
            kind: 'function',
          },
          {
            name: 'useAction',
            kind: 'function',
            url: '/api/react/use-action/',
          },
          {
            name: 'useCondition',
            kind: 'function',
            url: '/api/react/use-condition/',
          },
          {
            name: 'useEvent',
            kind: 'function',
            url: '/api/react/use-event/',
          },
          {
            name: 'useInlineTrigger',
            kind: 'function',
            url: '/api/react/use-inline-trigger/',
          },
          {
            name: 'useInspect',
            kind: 'function',
            url: '/api/react/use-inspect/',
          },
          {
            name: 'useInspectHistory',
            kind: 'function',
            url: '/api/react/use-inspect-history/',
          },
          {
            name: 'useRuntime',
            kind: 'function',
          },
          {
            name: 'useScope',
            kind: 'function',
          },
          {
            name: 'RUNTIME_KEY',
            kind: 'constant',
          },
          {
            name: 'SCOPE_KEY',
            kind: 'constant',
          },
          {
            name: 'TriggerRuntimeProvider',
            kind: 'component',
            url: '/api/react/trigger-runtime-provider/',
          },
          {
            name: 'TriggerScope',
            kind: 'component',
            url: '/api/react/trigger-scope/',
          },
          {
            name: 'UseInlineTriggerConfig',
            kind: 'type',
          },
        ],
      },
    ],
  },
  {
    id: 'testing',
    title: 'Testing',
    packages: [
      {
        name: '@triggery/testing',
        url: '/packages/testing/',
        blurb: 'headless runtime + fake scheduler + mocks',
        symbols: [
          {
            name: 'createFakeScheduler',
            kind: 'function',
          },
          {
            name: 'createTestRuntime',
            kind: 'function',
            url: '/api/testing/create-test-runtime/',
          },
          {
            name: 'FakeScheduler',
            kind: 'type',
            url: '/api/testing/fake-scheduler/',
          },
          {
            name: 'TestRuntime',
            kind: 'type',
          },
          {
            name: 'TestRuntimeOptions',
            kind: 'type',
          },
        ],
      },
    ],
  },
  {
    id: 'tooling',
    title: 'Tooling',
    packages: [
      {
        name: '@triggery/vite',
        url: '/packages/vite/',
        blurb: 'auto-import every *.trigger.ts',
        symbols: [
          {
            name: 'triggery',
            kind: 'function',
          },
          {
            name: 'TriggeryViteOptions',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/cli',
        url: '/packages/cli/',
        blurb: 'create / scaffold / graph / lint',
        symbols: [
          {
            name: 'buildTriggerGraph',
            kind: 'function',
          },
          {
            name: 'createProject',
            kind: 'function',
          },
          {
            name: 'isKnownTemplate',
            kind: 'function',
          },
          {
            name: 'renderGraph',
            kind: 'function',
          },
          {
            name: 'runLint',
            kind: 'function',
          },
          {
            name: 'scaffoldTrigger',
            kind: 'function',
          },
          {
            name: 'CreateProjectOptions',
            kind: 'type',
          },
          {
            name: 'CreateProjectResult',
            kind: 'type',
          },
          {
            name: 'GraphFormat',
            kind: 'type',
          },
          {
            name: 'GraphOptions',
            kind: 'type',
          },
          {
            name: 'LintOptions',
            kind: 'type',
          },
          {
            name: 'ScaffoldTriggerOptions',
            kind: 'type',
          },
          {
            name: 'TemplateName',
            kind: 'type',
          },
          {
            name: 'TriggerNode',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/codemod',
        url: '/packages/codemod/',
        blurb: 'ts-morph codemods',
        symbols: [
          {
            name: 'extractTrigger',
            kind: 'function',
            url: '/api/codemod/extract-trigger/',
          },
          {
            name: 'migrateFromListenerMiddleware',
            kind: 'function',
            url: '/api/codemod/migrate-from-listener-middleware/',
          },
          {
            name: 'ExtractTriggerOptions',
            kind: 'type',
          },
          {
            name: 'ExtractTriggerResult',
            kind: 'type',
          },
          {
            name: 'MigratedListener',
            kind: 'type',
          },
          {
            name: 'MigrateFromListenerMiddlewareOptions',
            kind: 'type',
          },
          {
            name: 'MigrateFromListenerMiddlewareResult',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/eslint-plugin',
        url: '/packages/eslint-plugin/',
        blurb: '8 rules + recommended / strict',
        symbols: [
          {
            name: 'recommended',
            kind: 'function',
            url: '/api/eslint-plugin/recommended/',
          },
          {
            name: 'rules',
            kind: 'function',
          },
          {
            name: 'strict',
            kind: 'function',
          },
        ],
      },
    ],
  },
  {
    id: 'adapters',
    title: 'State / event adapters',
    packages: [
      {
        name: '@triggery/redux',
        url: '/packages/redux/',
        blurb: 'Redux selectors as conditions',
        symbols: [
          {
            name: 'useReduxCondition',
            kind: 'function',
          },
          {
            name: 'ReduxStoreLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/zustand',
        url: '/packages/zustand/',
        blurb: 'Zustand slices as conditions',
        symbols: [
          {
            name: 'useZustandCondition',
            kind: 'function',
          },
          {
            name: 'ZustandStoreLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/jotai',
        url: '/packages/jotai/',
        blurb: 'Jotai atoms as conditions',
        symbols: [
          {
            name: 'useJotaiCondition',
            kind: 'function',
          },
          {
            name: 'JotaiAtomLike',
            kind: 'type',
          },
          {
            name: 'JotaiStoreLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/mobx',
        url: '/packages/mobx/',
        blurb: 'MobX observables as conditions',
        symbols: [
          {
            name: 'useMobxCondition',
            kind: 'function',
          },
        ],
      },
      {
        name: '@triggery/signals',
        url: '/packages/signals/',
        blurb: 'preact-signals / alien-signals',
        symbols: [
          {
            name: 'useSignalCondition',
            kind: 'function',
          },
          {
            name: 'SignalLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/reatom',
        url: '/packages/reatom/',
        blurb: 'Reatom v3 atoms as conditions',
        symbols: [
          {
            name: 'useReatomCondition',
            kind: 'function',
          },
          {
            name: 'ReatomReadableLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/query',
        url: '/packages/query/',
        blurb: 'TanStack Query cache lookups',
        symbols: [
          {
            name: 'useQueryCondition',
            kind: 'function',
          },
          {
            name: 'QueryClientLike',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/dom',
        url: '/packages/dom/',
        blurb: 'DOM events + ResizeObserver + IntersectionObserver',
        symbols: [
          {
            name: 'useDomEvent',
            kind: 'function',
          },
          {
            name: 'useIntersectionObserver',
            kind: 'function',
          },
          {
            name: 'useResizeObserver',
            kind: 'function',
          },
          {
            name: 'DomEventTarget',
            kind: 'type',
          },
          {
            name: 'UseDomEventOptions',
            kind: 'type',
          },
          {
            name: 'UseIntersectionObserverOptions',
            kind: 'type',
          },
          {
            name: 'UseResizeObserverOptions',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/socket',
        url: '/packages/socket/',
        blurb: 'socket.io-client + native WebSocket',
        symbols: [
          {
            name: 'useSocketIoEvent',
            kind: 'function',
          },
          {
            name: 'useWebSocketEvent',
            kind: 'function',
          },
          {
            name: 'SocketIoLike',
            kind: 'type',
          },
          {
            name: 'UseSocketIoEventOptions',
            kind: 'type',
          },
          {
            name: 'UseWebSocketEventOptions',
            kind: 'type',
          },
          {
            name: 'WebSocketLike',
            kind: 'type',
          },
        ],
      },
    ],
  },
  {
    id: 'devtools',
    title: 'DevTools',
    packages: [
      {
        name: '@triggery/devtools-redux',
        url: '/packages/devtools-redux/',
        blurb: 'Redux DevTools middleware',
        symbols: [
          {
            name: 'reduxDevtoolsMiddleware',
            kind: 'function',
          },
          {
            name: 'DevtoolsHistoryEntry',
            kind: 'type',
          },
          {
            name: 'DevtoolsReduxOptions',
            kind: 'type',
          },
          {
            name: 'DevtoolsState',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/devtools-panel',
        url: '/packages/devtools-panel/',
        blurb: 'InspectorView for in-app debug UIs',
        symbols: [
          {
            name: 'InspectorView',
            kind: 'component',
          },
          {
            name: 'TriggerSnapshotView',
            kind: 'component',
          },
          {
            name: 'InspectorViewProps',
            kind: 'type',
          },
          {
            name: 'TriggerSnapshotViewProps',
            kind: 'type',
          },
        ],
      },
      {
        name: '@triggery/devtools-bridge',
        url: '/packages/devtools-bridge/',
        blurb: 'page-side bridge for external panels',
        symbols: [
          {
            name: 'installDevtoolsBridge',
            kind: 'function',
          },
          {
            name: 'DEVTOOLS_GLOBAL_KEY',
            kind: 'constant',
          },
          {
            name: 'DEVTOOLS_SOURCE',
            kind: 'constant',
          },
          {
            name: 'DevtoolsBridgeOptions',
            kind: 'type',
          },
          {
            name: 'DevtoolsMessage',
            kind: 'type',
          },
        ],
      },
    ],
  },
];
